[package]
name = "client"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
chrono = "^0.4"
tabular = "0.1.2"
daggy = "0.6.0"
nom = "5.0.1"
yew = "0.9.2"
stdweb = "0.4.2"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3.27"
features = [
  "Window",
  "Document",
  "HtmlHeadElement",
  "HtmlElement"
]
