[package]
name = "binance-bot"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

[dependencies]
telegram-bot = "0.7"
serde_json = "^1"
async-tls = "^0.9"
rustls = "^0.18"
async-h1 = "^2"
http-types = "^2"
lazy_static = "^1.4"
clap = "^2"
regex = "^1.3"

[dependencies.chrono]
version = "^0.4"
features = [
  "serde",
]
[dependencies.futures]
version = "0.3"

[dependencies.tokio]
version = "0.2"
features = [
  "fs",
  "rt-threaded",
]

[dev-dependencies.tokio]
version = "0.2"
features = [
  "fs",
  "macros",
  "time"
]

[dependencies.async-std]
version = "^1.6"

[dependencies.futures-core]
version = "^0.3"

[dependencies.openlimits]
path = "../openlimits"

[dependencies.serde]
version = "^1"
features = [
  "derive",
]
