[package]
name = "binance-bot"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "^0.10"
telegram-bot = "0.7"
serde_json = "^1"

[dependencies.futures]
version = "0.3"

[dependencies.tokio]
version = "0.2"
features = [
  "fs"
]

[dev-dependencies.tokio]
version = "0.2"
features = [
  "fs",
  "macros",
  "time"
]

[dependencies.async-std]
version = "^1.6"

[dependencies.futures-core]
version = "^0.3"

[dependencies.binance]
git = "https://github.com/wisespace-io/binance-rs.git"

[dependencies.serde]
version = "^1"
features = [
  "derive",
]
