[package]
name = "budget_app"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

[dependencies]
chrono = "^0.4"
tabular = "^0.1"
daggy = "^0.6"
nom = "^5"
azul = { git = "https://github.com/mankinskin/azul" }
