[workspace]
members = [
  "plans",
  "budget",
  "interpreter",
  "database",
  "updatable",
  "derive_updatable",
  "server",
  "server/client",
  "server/api",
  "server/api/examples/rocket_server",
  "server/api/examples/rocket_server/seed_client",
]
