[package]
name = "server"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.0.0"
chrono = "0.4.11"
colored = "1.9.3"
serde_json = "1.0.51"
lazy_static = "1.4.0"

[dependencies.rql]
path = "../../rql"

[dependencies.plans]
path = "../plans"
