[package]
name = "server"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "^0.4"
chrono = "^0.4"
colored = "^1.9"
serde = "^1"
serde_json = "^1.0"
lazy_static = "^1.4"
anyhow = "^1"
uuid = "^0.8"

[dependencies.rql]
path = "../../rql"

[dependencies.rocket_contrib]
version = "^0.4"
default-features = false
features = [
  "json",
  "uuid",
]

[dependencies.plans]
path = "../plans"
