[package]
name = "server"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
chrono = "^0.4"
tabular = "0.1.2"
nom = "^5.1"
wasm-bindgen = "^0.2"
lazy_static = "1.4"

[dependencies.yew]
version = "^0.14"
features = [
  "std_web"
]

[dependencies.stdweb]
version = "^0.4"

[dependencies.plans]
path = "../plans"
