[package]
name = "server"
version = "0.1.0"
authors = ["Linus Behrbohm <linusbehrbohm@web.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "^3"
chrono = "^0.4"
colored = "^1"
serde_json = "^1"
rql = "^0.5"
lazy_static = "^1"

[dependencies.plans]
path = "../plans"
